version: "3.8"

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - API_KEY=${API_KEY}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - "3001:3001"
      - "4001:4001"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    command: ["redis-server", "--maxclients", "1000"]
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
