FROM koyeb/docker-compose

# Install Node.js and npm
RUN apk add --no-cache nodejs npm

# Copy the project files into the container
COPY . /app

# Install Node.js dependencies in the /app directory
WORKDIR /app

# Install all dependencies, including "concurrently"
RUN npm ci

# Set the entry point to run Docker Compose, which will handle the rest
CMD ["docker-compose", "up"]
